### ISSUE TITLE
Metal support

### ISSUE THREAD

**Issue by KatekovAnton** [rbfx/rbfx#372]
Hi. iOS and MacOS deprecated OpenGL few years ago. Instead, Apple introduced its own graphical API - [Metal](https://developer.apple.com/metal/)

Is it possible to adopt rbfx to this API? just to make sure that our projects will stay safe on this platform?

Thank you.

**Comment by rokups** [comment]
We were looking into some ways to achieve that. Most likely way is a third party (💡) graphics api abstraction. We were looking into nvrhi/TheForge/Dilligent. So far nothing fully fits the bill. WebGPU also looks very promising, but its still very early for that and i havent seen an implementation that isnt crazy and isnt written in rust..

**Comment by Alan-FGR** [comment]
Kinc and Sokol are both nice. The former is more modern and supports a lot of platforms, but it's not well documented and the differences in platforms are more transparent since it exposes the features in support level brackets, so I guess it could become a differently kind of xplat nightmare (except you have graphics1, 2, 3 instead of opengl, directx, metal), unless you're targeting the latest and greatest at which point webGPU could be a better option assuming there's not a lot of manpower here so targeting platforms that are going to be mainstream in a few years is reasonable.

Bgfx is also holding extremely well considering its age and the API style which is more like old T&L-on-GPU, but people are doing GPU-driven rendering on it and the abstraction is not breaking apart. It only goes so far though, and it's leaving some platforms behind asking the way. Notably WebGL which doesn't support threads and although there's an extension for indirect drawing that only Chrome(ium) supports, you can forget anything modern on it.

As for the main question here which seems to be about investing in something that might go deprecated soon, there's always ANGLE to save you. Performance is not the best, and honestly, I could be wrong and being unfair but it looks way too much overengineered, especially by seeing how other abstractions don't have the bazillion layers ANGLE has, but it's still a Chrome backend and being actively developed. So worst case scenario there's that. Also, it shouldn't be too hard to get the OpenGL backend of Rbfx and plug it into Sokol or Bgfx, iirc @boberfly once did some incredible work on that and got the fundamentals working.

Rbfx could use a fast ECS and Jolt integration though :trollface:

**Comment by Alan-FGR** [comment]
Also, don't forget that SDL3 will ship a modern thread-safe 3D rendering abstraction with a common GPU language and tailored for modern applications, so maybe that could also be something to have on the radar. Apparently it's going to support only the modern APIs. I'm following that closely; SDL is a bit massive but it's honestly the most reliable piece of tech I've ever used.

**Comment by KatekovAnton** [comment]
Yesterday we (me, Gleb and Eugene) discovered a weird problem in SDL - seems that it is trying to sync to 120fps that causes major system slowdown. Result - not just game, but the entire system FPS dropped to 2-3 FPS

![video](https://i.gyazo.com/be2b395bb5ff9cb2fc2ba443ccf81ee0.mp4)


Some info about this:
https://github.com/glfw/glfw/issues/1990

I applied following change to sdl
https://github.com/libsdl-org/SDL/commit/13869f194c5b975aefac6517e58998f11108d722

My implementation for modern objc:
https://github.com/KatekovAnton/rbfx/commit/196cf25ef17c22c08f0139e32e21e2b9d5c6cb1c

**Comment by KatekovAnton** [comment]
Yesterday we (me Gleb and Eugene) discovered a weird issue with SDL. Seems that it is trying to do vsync to 120fps isntead of 60 on mac. Result - a major system slowdown after 1 min of the app running. Video: https://i.gyazo.com/be2b395bb5ff9cb2fc2ba443ccf81ee0.mp4

More info about the issue https://github.com/glfw/glfw/issues/1990

We applied following patch https://github.com/libsdl-org/SDL/commit/13869f194c5b975aefac6517e58998f11108d722

The patch adopted to modern objc syntax https://github.com/KatekovAnton/rbfx/commit/196cf25ef17c22c08f0139e32e21e2b9d5c6cb1c

**Comment by eugeneko** [comment]
Metal is supported via MoltenVK, although it would require some configuration on the user side (MoltenVK should be installed by the user and visible for CMake when building the engine).

Mac users are welcome to polish this pipeline, I cannot really do anything due to zero macs in my area.
