### ISSUE TITLE
DeferredDecal disappear if camera gets close

### ISSUE THREAD

**Issue by crystaldev3d** [rbfx/rbfx#466]
Hi! I just took a look at the decals and discovered a bug.
The decals disappear if the camera goes into the volume of the decal. 
For this reason they cannot be used on objects closest to the camera. 
Is there any way to reduce the volume? Or create a special flattened cube (by one axis) for decals?
here is two pics.
![c1](https://user-images.githubusercontent.com/95735962/187598218-8549e770-0b9d-4304-b0bd-6fc9b6eff165.jpg)
![c2](https://user-images.githubusercontent.com/95735962/187598226-25191343-7956-49c1-bc1c-7da09cd90e63.jpg)

**Comment by gleblebedev** [comment]
This is expected. In real life application the decal box should be thin and close to surface. I guess I should do the same in the showcase scene.

**Comment by crystaldev3d** [comment]
I don't think that is expected)
it's bug, there need some workaround for drawable boundaries when Decal are rendered (force to render)
here is picture from U4, I can move camera very close to decal.
![c11](https://user-images.githubusercontent.com/95735962/187662306-bd66aa92-a929-4050-9166-ceebeec473eb.jpg)
![c22](https://user-images.githubusercontent.com/95735962/187662335-ca53a6be-824d-4861-a751-9d8e9937a7ed.jpg)

**Comment by eugeneko** [comment]
We can solve that by writing custom code for decal rendering instead of reusing default box model renderer.
It's doable, but it will just need significantly more work on renderer side.

There is quick and dirty hack to do what you want:
![image](https://user-images.githubusercontent.com/8576192/187669738-d0ea0283-62bf-4b84-a8b1-ede023a2e676.png)
You lose benefits of depth testing for far decals, but you get 100% correct and visible decals.

Ideally we should just toggle this stuff based on distance to bounding box, like deferred light volumes do.

Well, ackshually.... Let's just do quick and dirty workaround.
